import { EventType } from "../../type/EventType";

const mockEvents = [
  {
    id: "1",
    title: "มวยโคราช AMAZING MUAY THAI EXPEREIENCE",
    start: "2024-09-06T16:30:00",
    end: "2024-09-08T18:30:00",
    eventType: "Festival" as EventType,
    image: "/มวยโคราช พิมาย.jpg",
    detail: `🔥 ☄️ เปิดคู่ความมันส์ “ศึกมหัสจรรย์มวยไทย” ในงาน AMAZING MUAY THAI EXPEREIENCE จัดหนักจัดเต็มตลอด 3 วัน กว่า 21 คู่ชก รับชมความมันส์กันฟรี ๆ แบบติดขอบเวทีได้ที่ลานเมรุพรหมทัต อ.พิมาย จ.นครราชสีมา ตั้งแต่เวลา 16.30 - 18.30 น. วันที่ 6 - 8 กันยายน 2567
      .
      🥊 ร่วมสัมผัสประสบการณ์การเรียนมวยไทยกับบรมครูมวยไทยโบราณ อย่าง “มวยโคราช” ในงาน AMAZING MUAY THAI EXPEREIENCE วันที่ 6 - 8 กันยายน 2567 ณ ลานเมรุพรหมทัต อ.พิมาย จ.นครราชสีมา เวลา 16.00 - 22.00 น.
      .
      #amazingmuaythaiexperience #muaythai #amazingthailand #softpower #มวยไทย #มวยไทยโบราณ #หมัดหนักโคราช #ฉลาดลพบุรี #ท่าดีไชยา #ไวกว่าท่าเสา #สุราษฎร์ธานี #อุตรดิตถ์ #นครราชสีมา #ลพบุรี
      🔥 ☄️ เปิดคู่ความมันส์ “ศึกมหัสจรรย์มวยไทย” ในงาน AMAZING MUAY THAI EXPEREIENCE จัดหนักจัดเต็มตลอด 3 วัน กว่า 21 คู่ชก รับชมความมันส์กันฟรี ๆ แบบติดขอบเวทีได้ที่ลานเมรุพรหมทัต อ.พิมาย จ.นครราชสีมา ตั้งแต่เวลา 16.30 - 18.30 น. วันที่ 6 - 8 กันยายน 2567
      .
      🥊 ร่วมสัมผัสประสบการณ์การเรียนมวยไทยกับบรมครูมวยไทยโบราณ อย่าง “มวยโคราช” ในงาน AMAZING MUAY THAI EXPEREIENCE วันที่ 6 - 8 กันยายน 2567 ณ ลานเมรุพรหมทัต อ.พิมาย จ.นครราชสีมา เวลา 16.00 - 22.00 น.
      .
      #amazingmuaythaiexperience #muaythai #amazingthailand #softpower #มวยไทย #มวยไทยโบราณ #หมัดหนักโคราช #ฉลาดลพบุรี #ท่าดีไชยา #ไวกว่าท่าเสา #สุราษฎร์ธานี #อุตรดิตถ์ #นครราชสีมา #ลพบุรี`,
    location_link: "https://maps.app.goo.gl/QXZUvnbdrxsph8yZ8",
    page_link: "https://www.facebook.com/share/p/i1stDcrQ4vwQrvQc/",
    register_link: "",
  },
  {
    id: "2",
    title: "Design Review",
    start: "2024-09-11T00:00:00",
    end: "2024-09-11T23:59:59",
    eventType: "Food" as EventType,
    image: "/1image.png",
    detail: "",
    location_link: "https://maps.app.goo.gl/QXZUvnbdrxsph8yZ8",
    page_link: "https://www.facebook.com/share/p/i1stDcrQ4vwQrvQc/",
    register_link: "",
  },
  {
    id: "3",
    title: "Project ArtandMusic",
    start: "2024-09-12T00:00:00",
    end: "2024-09-12T23:59:59",
    eventType: "ArtandMusic" as EventType,
    image: "/2image.png",
    detail: "",
    location_link: "https://maps.app.goo.gl/QXZUvnbdrxsph8yZ8",
    page_link: "https://www.facebook.com/share/p/i1stDcrQ4vwQrvQc/",
    register_link: "",
  },
  {
    id: "4",
    title: "Client Presentation",
    start: "2024-09-13T00:00:00",
    end: "2024-09-13T23:59:59",
    eventType: "Food" as EventType,
    image: "/3image.png",
    detail: "",
    location_link: "https://maps.app.goo.gl/QXZUvnbdrxsph8yZ8",
    page_link: "https://www.facebook.com/share/p/i1stDcrQ4vwQrvQc/",
    register_link: "",
  },
  {
    id: "5",
    title: "Code Review",
    start: "2024-09-14T00:00:00",
    end: "2024-09-14T23:59:59",
    eventType: "Sport" as EventType,
    image: "/4image.png",
    detail: "",
    location_link: "https://maps.app.goo.gl/QXZUvnbdrxsph8yZ8",
    page_link: "https://www.facebook.com/share/p/i1stDcrQ4vwQrvQc/",
    register_link: "",
  },
  {
    id: "6",
    title: "Design Review",
    start: "2024-09-15T00:00:00",
    end: "2024-09-15T23:59:59",
    eventType: "Sport" as EventType,
    image: "/ChompolFest.jpg",
    detail: "",
    location_link: "https://maps.app.goo.gl/QXZUvnbdrxsph8yZ8",
    page_link: "https://www.facebook.com/share/p/i1stDcrQ4vwQrvQc/",
    register_link: "",
  },
  {
    id: "7",
    title: "ArtandMusic Meeting",
    start: "2024-09-15T00:00:00",
    end: "2024-09-15T23:59:59",
    eventType: "ArtandMusic" as EventType,
    image: "/ChompolFest.jpg",
    detail: "",
    location_link: "https://maps.app.goo.gl/QXZUvnbdrxsph8yZ8",
    page_link: "https://www.facebook.com/share/p/i1stDcrQ4vwQrvQc/",
    register_link: "",
  },
  {
    id: "8",
    title: "ArtandMusic Meeting",
    start: "2024-09-15T00:00:00",
    end: "2024-09-15T23:59:59",
    eventType: "ArtandMusic" as EventType,
    image: "/ChompolFest.jpg",
    detail: "",
    location_link: "https://maps.app.goo.gl/QXZUvnbdrxsph8yZ8",
    page_link: "https://www.facebook.com/share/p/i1stDcrQ4vwQrvQc/",
    register_link: "",
  },
  {
    id: "9",
    title: "ArtandMusic Meeting",
    start: "2024-09-15T00:00:00",
    end: "2024-09-15T23:59:59",
    eventType: "ArtandMusic" as EventType,
    image: "/ChompolFest.jpg",
    detail: "",
    location_link: "https://maps.app.goo.gl/QXZUvnbdrxsph8yZ8",
    page_link: "https://www.facebook.com/share/p/i1stDcrQ4vwQrvQc/",
    register_link: "",
  },
  {
    id: "10",
    title: "ArtandMusic Meeting",
    start: "2024-09-15T00:00:00",
    end: "2024-09-15T23:59:59",
    eventType: "ArtandMusic" as EventType,
    image: "/ChompolFest.jpg",
    detail: "",
    location_link: "https://maps.app.goo.gl/QXZUvnbdrxsph8yZ8",
    page_link: "https://www.facebook.com/share/p/i1stDcrQ4vwQrvQc/",
    register_link: "",
  },
  {
    id: "11",
    title: "ArtandMusic Meeting",
    start: "2024-09-15T00:00:00",
    end: "2024-09-15T23:59:59",
    eventType: "ArtandMusic" as EventType,
    image: "/ChompolFest.jpg",
    detail: "",
    location_link: "https://maps.app.goo.gl/QXZUvnbdrxsph8yZ8",
    page_link: "https://www.facebook.com/share/p/i1stDcrQ4vwQrvQc/",
    register_link: "",
  },
  {
    id: "12",
    title: "ArtandMusic Meeting",
    start: "2024-09-15T00:00:00",
    end: "2024-09-15T23:59:59",
    eventType: "ArtandMusic" as EventType,
    image: "/ChompolFest.jpg",
    detail: "",
    location_link: "https://maps.app.goo.gl/QXZUvnbdrxsph8yZ8",
    page_link: "https://www.facebook.com/share/p/i1stDcrQ4vwQrvQc/",
    register_link: "",
  },
  {
    id: "13",
    title: "ArtandMusic Meeting",
    start: "2024-09-15T00:00:00",
    end: "2024-09-15T23:59:59",
    eventType: "ArtandMusic" as EventType,
    image: "/ChompolFest.jpg",
    detail: "",
    location_link: "https://maps.app.goo.gl/QXZUvnbdrxsph8yZ8",
    page_link: "https://www.facebook.com/share/p/i1stDcrQ4vwQrvQc/",
    register_link: "",
  },
];

export default mockEvents;
